# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
################################################################################
#
#   Section: Organizations
#
#   - This section defines the different organizational identities which will
#   be referenced later in the configuration.
#
################################################################################
Organizations:
    - &benhvienthanhthuyendxquang
        # DefaultOrg defines the organization which is used in the sampleconfig
        # of the fabric.git development environment
        Name: benhvienthanhthuyendxquangMSP

        # ID to load the MSP definition as
        ID: benhvienthanhthuyendxquangMSP

        MSPDir: ../organizations/peerOrganizations/benhvienthanhthuyendxquang.example.com/msp

        Policies:
            Readers:
                Type: Signature
                Rule: "OR('benhvienthanhthuyendxquangMSP.admin', 'benhvienthanhthuyendxquangMSP.peer', 'benhvienthanhthuyendxquangMSP.client')"
            Writers:
                Type: Signature
                Rule: "OR('benhvienthanhthuyendxquangMSP.admin', 'benhvienthanhthuyendxquangMSP.client')"
            Admins:
                Type: Signature
                Rule: "OR('benhvienthanhthuyendxquangMSP.admin')"
            Endorsement:
                Type: Signature
                Rule: "OR('benhvienthanhthuyendxquangMSP.peer')"
